/// Flutter icons MtgManaCustom
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MtgManaCustom
///      fonts:
///       - asset: fonts/MtgManaCustom.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

abstract class MtgManaCustom {
  MtgManaCustom._();

  static const _kFontFam = 'MtgManaCustom';
  static const String? _kFontPkg = null;

  static const IconData 5 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData 6 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData 7 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData 8 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData 9 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData 10 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData b = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData c = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData e = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData g = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData p = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData r = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData s = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData u = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData w = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData w_list = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData w_original = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData z = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData 0 = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData 1 = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData 2 = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData 3 = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData 4 = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
